---
npm:
  platforms:
    - name: linux
      os: ubuntu
      architecture: x86_64
      node_versions:
        - "10"
        - "12"
        - "14"
    - name: linux
      os: alpine
      architecture: x86_64
      node_versions:
        - "10"
        - "12"
        - "14"

docker:
  publish: false
